### PR TITLE
autoBlueprints.xml.appends   fr.po

### PR DESCRIPTION
**Pull request by THETASOLA**
This is a bulk translation of the autoBlueprints in french.

The workflow on this file was the following:
- Running googletrans API on the file instances of "msgstr"
- Bulk correction with find & replace tool of the most visible error
- Entry by entry checking/making correct translation (moslty to find the most errogenous error to find & replace for the whole file) (I only did this for 1/4 of the file, there is to many entries for one sane mind)
- (Really) quick reading of the entire file to check for some big errors

Given the workflow, this is far from being an exact 100% translation without error but it should still be easier for weblate french user to achieve translation of this huge (and quite repetitive) file.

Issue: I would have loved to add the "Need editing" tag to every entry to "force" a proofreading of this crude translation, perhaps you could tell me how to do so.

### CODE REVIEW

**Comment by nedsociety** [comment]
> Running googletrans API on the file instances of "msgstr"

Did you read it with a proper .po parser? It's far from a plain string format so I'm asking just in case.

> Issue: I would have loved to add the "Need editing" tag to every entry to "force" a proofreading of this crude translation, perhaps you could tell me how to do so.

The flag named "fuzzy" (`#, fuzzy`) corresponds to the Needs Editing checkbox in Weblate.

@arbaes, could you make decision here?

**Comment by arbaes** [comment]
I don't mind if the Fuzzy flag is set, as some terms were already translated in other files by Jersee and the OG french team, it will ensure consistency with the help of the Glossary hopefully.

**Comment by nedsociety** [comment]
I mean, are the French team okay with introducing MT'd text without full review?

**Comment by arbaes** [comment]
Either way this specific file will have to be reviewed properly as it's a pretty sensible one. I'll check more deeply the quality of the translations later, google translate is more often wrong than right unfortunatly

**Comment by THETASOLA** [comment]
> google translate is more often wrong than right unfortunatly

Well yes that is the main issue I encountered


> Did you read/write it with a proper .po parser? It's far from a plain string so I'm asking just in case.

No, so I guess it is better to close this request

**Comment by nedsociety** [comment]
If you're fluent at Python then you might be able to easily write a script (see `snippets/` directory for examples) to read po, extract strings and flag them as fuzzy.

Closing per request.

**Pull request closed without merging**
